# Generated by Django 3.2.4 on 2021-06-19 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Link name')),
                ('link', models.URLField(verbose_name='URL')),
                ('icon', models.TextField(choices=[('im im-github', 'GitHub'), ('im im-stackoverflow', 'StackOverflow'), ('im im-linkedin', 'LinkedIn'), ('im im-twitter', 'Twitter'), ('im im-globe', 'Website')], verbose_name='Icon name')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Skill name')),
                ('description', models.TextField(verbose_name='Skill description')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='default.jpg', upload_to='avatars')),
                ('summary', models.TextField(verbose_name='Summary about user')),
                ('location', models.TextField(verbose_name='Place of residence')),
                ('about', models.TextField(verbose_name='About')),
                ('other_skills', models.TextField(verbose_name='Other skills')),
                ('links', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Links', to='users.link')),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Skills', to='users.skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
