# Generated by Django 3.2.4 on 2021-06-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='links',
        ),
        migrations.AddField(
            model_name='account',
            name='links',
            field=models.ManyToManyField(related_name='Links', to='users.Link'),
        ),
        migrations.RemoveField(
            model_name='account',
            name='skills',
        ),
        migrations.AddField(
            model_name='account',
            name='skills',
            field=models.ManyToManyField(related_name='Skills', to='users.Skill'),
        ),
    ]
