# Generated by Django 3.2.4 on 2021-06-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210619_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='about',
            field=models.TextField(default='Apparently, this user prefers to keep an air of mystery about them.', verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(default='/avatars/default.jpg', upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='account',
            name='location',
            field=models.TextField(default='Location is not specified.', verbose_name='Place of residence'),
        ),
        migrations.AlterField(
            model_name='account',
            name='summary',
            field=models.TextField(default='New user on our platform!', verbose_name='Summary about user'),
        ),
    ]
