# Generated by Django 3.2.4 on 2021-06-19 16:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_account_other_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='other_skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30, verbose_name='Other skills'), null=True, size=None),
        ),
    ]
